### ISSUE TITLE
카테고리, 댓글 API 개발

### ISSUE THREAD

**Issue by Jungsu-lilly** [nodak-v2/Nodak-Server#17]
## Description 📝
* 댓글, 카테고리 API를 개발합니다.

## TODO ✅
- [x] 댓글 API 개발
  - [x] mvc 패턴
  - [x] service단 테스트 코드 작성
- [x] 카테고리 API 개발
  - [x] mvc 패턴
  - [x] service단 테스트 코드 작성
