### ISSUE TITLE
[Feat] 투표 엔티티 구현

### ISSUE THREAD

**Issue by wooyong99** [nodak-v2/Nodak-Server#2]
## Description 📝
* 투표 도메인의 엔티티를 구현한다.
## TODO ✅
- [x] Entity 구현
  - [x] Vote 엔티티 구현
  - [x] VoteOption 엔티티 구현
  - [x] VoteHistory 엔티티 구현
- [ ] 테스트 코드 작성
  - [ ] Vote 테스트 코드 작성
  - [x] VoteOption 테스트 코드 작성
  - [ ] VoteHistory 테스트 코드 작성
