### ISSUE TITLE
투표 시작일/종료일 추가, 투표 강제 종료 기능 구현

### ISSUE THREAD

**Issue by Jungsu-lilly** [nodak-v2/Nodak-Server#98]
## Description 📝
* 투표 API 전반을 리팩토링, 기능을 추가합니다.

## TODO ✅
- [x] 투표 시작 날짜, 종료 날짜 컬럼 추가
- [x] 투표 종료 여부를 나타내는 필드 추가 (terminated)
- [x] 투표를 강제로 종료 기능 추가
- [x] 게시글 조회 시, 투표 선택지 출력
